robin-v2-7b:
    prompt_template: "robin-v2-7b/prompt.txt"
    fn_completions: "huggingface_local_completions"
    completions_kwargs:
        model_name: "LMFlow/Full-Robin-7b-v2"
        model_kwargs:
            torch_dtype: 'bfloat16'
        max_new_tokens: 1800
        temperature: 0.7
        top_p: 1.0
        do_sample: True
    pretty_name: "Robin 7b v2"
    link: "https://huggingface.co/LMFlow/Full-Robin-7b-v2"
